#!/bin/sh
dev=$(fw_printenv -n wlandev)
mac=$(fw_printenv -n wlanmac)
net=$(fw_printenv -n netaddr_fallback)
eth=$(fw_printenv -n ethaddr)

set_wireless() {
	path=/etc/wireless
	if $path/usb "$dev" || $path/sdio "$dev"; then
		[ -n "$mac" ] && ip link set dev wlan0 address "$mac"
		ifup wlan0
	elif $path/modem "$dev"; then
		ifup usb0
		ifup eth1
	fi
}

start() {
	echo "Starting wireless..."
	ifup lo
	if [ -n "$dev" ]; then
		set_wireless
	fi
	echo "Starting ethernet..."
	ifup eth0
}

stop() {
	echo "Stopping network..."
	ifdown lo
	ifdown -f wlan0
	ifdown -f usb0
	ifdown -f eth1
	ifdown -f eth0
}

case "$1" in
	start|stop)
		$1
		;;

	restart|reload)
		stop
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
