#!/bin/sh

DAEMON="/usr/bin/masinaclient"
PIDFILE="/var/run/client.pid"
DAEMON_ARGS=""

start() {
    ulimit -c unlimited
    echo "/tmp/core.client" > /proc/sys/kernel/core_pattern

    echo -n "Starting Masina client..."
    start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
}

stop() {
    echo -n "Stopping Masina client: "
    start-stop-daemon -K -q -p "$PIDFILE"
    if [ $? -eq 0 ]; then
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "FAIL"
    fi
}

case "$1" in
    start|stop)
        $1
        ;;

    restart|reload)
        stop
        sleep 3
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
        ;;
esac
